### ISSUE TITLE
Demo from README not working on astrolab machines

### ISSUE THREAD

**Issue by bmorris3** [jakevdp/multiband_LS#3]
We are doing a demo in PreMAP today on reproducibility in science, and can't reproduce the demo. Here's the error that we're getting for Figure 1: 

```python
(/astro/users/bmmorris/.conda/envs/multibandLS)bash-4.1$ python fig01_basic_example.py 
Traceback (most recent call last):
  File "fig01_basic_example.py", line 56, in <module>
    phase = (t / model.best_period) % 1
  File "/astro/users/bmmorris/.conda/envs/multibandLS/lib/python3.4/site-packages/gatspy/periodic/modeler.py", line 152, in best_period
    self._best_period = self._calc_best_period()
  File "/astro/users/bmmorris/.conda/envs/multibandLS/lib/python3.4/site-packages/gatspy/periodic/modeler.py", line 162, in _calc_best_period
    return self.optimizer.best_period(self)
  File "/astro/users/bmmorris/.conda/envs/multibandLS/lib/python3.4/site-packages/gatspy/periodic/optimizer.py", line 14, in best_period
    return_scores=False)
  File "/astro/users/bmmorris/.conda/envs/multibandLS/lib/python3.4/site-packages/gatspy/periodic/optimizer.py", line 83, in find_best_periods
    omega_min = 2 * np.pi / np.max(self.period_range)
  File "/astro/users/bmmorris/.conda/envs/multibandLS/lib/python3.4/site-packages/gatspy/periodic/optimizer.py", line 49, in period_range
    raise ValueError("period_range must be set in optimizer in order "
ValueError: period_range must be set in optimizer in order to find the best periods. For example:
 >>> model = LombScargle(fit_period=True)
 >>> model.optimizer.period_range = (0.2, 1.0)
```
We're using: Py 3.4.3 on Scientific Linux.

**Comment by jakevdp** [comment]
Thanks! Should be fixed in https://github.com/jakevdp/multiband_LS/commit/7733e54d93a4c20346384301d59b190a77b72267

It is due to an API change in the most recent ``gatspy`` release – we no longer set the optimizer range by default, because some thought must go into choosing the right range for each specific problem.
